[custom]
;参考：https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash/config

ruleset=🚫 拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🚫 拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🚫 拦截,https://anti-ad.net/surge.txt
ruleset=🚫 拦截,[]DOMAIN-SUFFIX,adobe.io
ruleset=🚫 拦截,[]DOMAIN-SUFFIX,adobestats.io
ruleset=🏠 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🏠 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🏠 直连,[]DOMAIN-SUFFIX,chiphell.com
ruleset=🌐 代理,[]DOMAIN-SUFFIX,grok.com
ruleset=🌐 代理,[]DOMAIN-SUFFIX,x.ai
ruleset=💬 AI,[]DOMAIN,alkalimakersuite-pa.clients6.google.com
ruleset=💬 AI,[]DOMAIN,feedback-pa.googleapis.com
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=💬 AI,[]DOMAIN-SUFFIX,spacex.com
ruleset=💬 AI,[]DOMAIN-SUFFIX,truthsocial.com
ruleset=🌐 代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🌐 代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌐 代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🏠 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🏠 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🏠 直连,[]GEOIP,CN
ruleset=🏠 直连,[]GEOIP,LAN
ruleset=🔚 兜底,[]FINAL

custom_proxy_group=🌐 代理`select`.*`[]DIRECT`
custom_proxy_group=💬 AI`select`[]🌐 代理`[]DIRECT`.*
custom_proxy_group=🏠 直连`select`[]DIRECT`[]🌐 代理`
custom_proxy_group=🚫 拦截`select`[]REJECT`[]🌐 代理`[]DIRECT`
custom_proxy_group=🔚 兜底`select`[]🌐 代理`[]DIRECT`
 
enable_rule_generator=true
overwrite_original_rules=true
