[custom]
;参考：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_Ai.ini


ruleset=🚫 拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🚫 拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🚫 拦截,https://anti-ad.net/surge.txt

ruleset=🚫 拦截,[]DOMAIN-SUFFIX,adobe.io
ruleset=🚫 拦截,[]DOMAIN-SUFFIX,adobestats.io
ruleset=🧱 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🧱 直连,[]DOMAIN-SUFFIX,chiphell.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,grok.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,x.ai
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=💬 AI,[]DOMAIN-SUFFIX,spacex.com
ruleset=💬 AI,[]DOMAIN-SUFFIX,truthsocial.com

ruleset=🧱 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🧱 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🧱 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🧱 直连,[]GEOIP,LAN
ruleset=🧱 直连,[]GEOIP,CN
ruleset=🔚 最终,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]DIRECT`.*
custom_proxy_group=💬 AI`select`[]🚀 节点选择`[]🧱 直连`.*
custom_proxy_group=🧱 直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚫 拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🔚 最终`select`[]🚀 节点选择`[]🧱 直连`.*
 
enable_rule_generator=true
overwrite_original_rules=true
